#pragma once

#define XLOG_TIME_BASE 0

#define XLOG_TTI_INDICATED (XLOG_TIME_BASE+1)

#define XLOG_TASK_BASE 100
#define XLOG_TASK_GEN (XLOG_TASK_BASE+1)
//#define XLOG_TASK_SCHED (XLOG_TASK_BASE+2)
#define XLOG_TASK_EXEC (XLOG_TASK_BASE+3)
#define XLOG_TASK_FINISH (XLOG_TASK_BASE+4)
//#define XLOG_TASK_ABORT (XLOG_TASK_BASE+5)
//#define XLOG_TASK_SUSPEND (XLOG_TASK_BASE+6)
//#define XLOG_TASK_RESUME (XLOG_TASK_BASE+7)



